2019-02-03 19:02:45,965 ERROR: Exception on /callback/q [GET] [in c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\omer\Desktop\Apple2Spotify\app\routes.py", line 118, in callback
    Convert.after_token(access_token)
  File "C:\Users\omer\Desktop\Apple2Spotify\app\convert.py", line 119, in after_token
    search = Search(playlist=PLAYLIST_URL, spusername=username, playlistname=playlist_name, author=current_user)
  File "<string>", line 4, in __init__
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\sqlalchemy\orm\state.py", line 424, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\sqlalchemy\util\compat.py", line 249, in reraise
    raise value
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\sqlalchemy\orm\state.py", line 421, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 762, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 229, in __set__
    instance_dict(instance), value, None)
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 815, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 835, in fire_replace_event
    state, value, previous, initiator or self._replace_token)
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 1183, in emit_backref_from_scalar_set_event
    child_state, child_dict = instance_state(child),\
  File "c:\users\omer\desktop\apple2spotify\venv\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute '_sa_instance_state'
2019-02-03 19:04:55,557 INFO: Apple2Spotify startup [in C:\Users\omer\Desktop\Apple2Spotify\app\__init__.py:48]
2019-02-04 13:07:21,509 INFO: Apple2Spotify startup [in C:\Users\omer\Desktop\Apple2Spotify\app\__init__.py:48]
2019-02-04 13:08:07,981 INFO: Apple2Spotify startup [in C:\Users\omer\Desktop\Apple2Spotify\app\__init__.py:48]
